export const userTypes = {
    SET_EMAIL_LOGIN: 'SET_EMAIL_LOGIN',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',

    SET_ADDRESSES: 'SET_ADDRESSES',
    SET_ADDRESSES_LOADING: 'SET_ADDRESSES_LOADING',
    SET_USER: 'SET_USER',
    SET_LOADING_LOGIN_REGISTER: 'SET_LOADING_LOGIN_REGISTER'
}

export const homeTypes = {
    SET_CATEGORY_BOOK: 'SET_CATEGORY_BOOK',
    SET_PUBLISHSER: "SET_PUBLISHSER",
    SET_PAGE: 'SET_PAGE',
    SET_BOOK: 'SET_BOOK',
    SET_SORT_TYPE: 'SET_SORT_TYPE',
    SET_RANGE: 'SET_RANGE',
    SET_NAME_TITLE_ITEM: 'SET_NAME_TITLE_ITEM',
    RESET_BOOK: 'RESET_BOOK',
    SET_BRANCH_SEARCH_BOOK:'SET_BRANCH_SEARCH_BOOK', 
    SET_SEARCH_TEXT: 'SET_SEARCH_TEXT',
    SET_AUTHOR: 'SET_AUTHOR',
    SET_ID_BRANCH: 'SET_ID_BRANCH',
    SET_HOME_PAGE: 'SET_HOME_PAGE',
    SET_TOTAL_PAGE: 'SET_HOME_TOTAL_PAGE',
    SET_BANNER: 'SET_BANNER'
}

export const productTypes = {
    SET_PRODUCT_DETAIL: 'SET_PRODUCT_DETAIL',
    SET_BOOK_RELATED: 'SET_BOOK_RELATED',
    SET_COMMENT: 'SET_COMMENT',
    SET_PAGE: 'SET_PAGE',
    SET_TOTAL_PAGE: 'SET_TOTAL_PAGE',
    SET_FILTER: 'SET_FILTER',
    SET_ALL_BOOK: 'SET_ALL_BOOK',
    SET_LOADING_PRODUCTS_DATA: 'SET_LOADING_PRODUCTS_DATA'
}
export const sortTypes =  {
    SORT_DAY_INCREASED: 'SORT_DAY_INCREASED',
    SORT_DAY_DECREASED: 'SORT_DAY_DECREASED',
    SORT_VIEWS_INCREASED: 'SORT_VIEWS_INCREASED',
    SORT_VIEWS_DECREASED: 'SORT_VIEWS_DECREASED',
    SORT_SALES_INCREASED: 'SORT_SALES_INCREASED',
    SORT_SALES_DECREASED: 'SORT_SALES_DECREASED',
    SORT_PRICE_INCREASED: 'SORT_PRICE_INCREASED',
    SORT_PRICE_DECREASED: 'SORT_PRICE_DECREASED',

}
export const cartTypes = {
    SET_CART: 'SET_CART',
    SET_CITY: 'SET_CITY',
    SET_DICTRICT: 'SET_DISTRICT',
    SET_WARD: 'SET_WARD',
    PAYMENT_SUCCESS: 'PAYMENT_SUCCESS',
    PAYMENT_FAIL: 'PAYMENT_FAIL',
    RESET_PAYMENT: 'RESET_PAYMENT',
    SET_ADD_TO_CART_LOADING: 'SET_ADD_TO_CART_LOADING'
}
export const billTypes = {
    SET_BILL: 'SET_BILL',
    SET_BILLS: 'SET_BILLS'
}
export const purchaseHistoryTypes = {
    SET_PURCHASED_HISTORY: 'SET_PURCHASED_HISTORY',
}

export const url = {
    URL_BE: 'http://localhost:8080/'
}